
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Identity1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BookedBy
{

    public int Id { get; set; }

    public string MembershipNo { get; set; }

    public int GymClassId { get; set; }



    public virtual GymClass GymClass { get; set; }

}

}
