
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Identity1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GymClass
{

    public GymClass()
    {

        this.BookedBies = new HashSet<BookedBy>();

    }


    public int Id { get; set; }

    public System.DateTime Date { get; set; }

    public short Duration { get; set; }

    public int ActivityId { get; set; }

    public int RoomId { get; set; }



    public virtual Activity Activity { get; set; }

    public virtual Room Room { get; set; }

    public virtual ICollection<BookedBy> BookedBies { get; set; }

}

}
