

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Identity1.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Model1Container : DbContext
{
    public Model1Container()
        : base("name=Model1Container")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<GymClass> GymClasses { get; set; }

    public virtual DbSet<ClassBooking> ClassBookings { get; set; }

    public virtual DbSet<MemberLog> MemberLogs { get; set; }

    public virtual DbSet<BookedBy> BookedBies { get; set; }

}

}

