//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.GymClasses = new HashSet<GymClass>();
        }
    
        public int Id { get; set; }
        public string RoomName { get; set; }
    
        public virtual ICollection<GymClass> GymClasses { get; set; }
    }
}
